### ISSUE TITLE
Is http://qamail.ala.se considering for usage ?

### ISSUE THREAD

**Issue by ajoecker** [naushniki/qamail#1]
HI,

i was wondering, whether http://qamail.ala.se is considered as actual endpoint to be used in one's project. Or shall it be solely an example and one should install the project locally ?

I simply tried to send a PUT request to `http://qamail.ala.se/api/create_session`, but it returns a `Internal Server Error`, so I was wondering whether this is by default or just an error on my side

thanks

**Comment by naushniki** [comment]
Hi!

-  http://qamail.ala.se is intended for demonstration only and may be down for considerable periods of time. Therefore I advice not to use it for actual work.


-  > I simply tried to send a PUT request to http://qamail.ala.se/api/create_session, but it returns a Internal Server Error, 

This looks like a bug. I will look into this tomorrow. To be honest, the API is not well tested, because I do not use it myself. Your feedback is very much welcome!

**Comment by naushniki** [comment]
[Fixed.](https://github.com/naushniki/qamail/commit/e5f3b8bb64173941b4864008f386330e66e0b7b2)
If you like [Postman](https://www.getpostman.com/), you can use [this collection](https://github.com/naushniki/qamail/blob/master/QAMail.postman_collection.json) to get to know the API.
